### ISSUE TITLE
debugging dapps

### ISSUE THREAD

**Issue by TheGoldenEye** [LiskHQ/lisk-sandbox#2]
The debugger don't stop at a breakpoint in the dapp.
Breakpoints in the main lisk sources are working, but not in the dapp code.
The dapp is running in a sandbox with the special node host ./nodejs/node . How I can enable debugging for this node process?
Maybe this is related:
If I start the node-inspector, I get the following error:

```
$ node-debug 
Node Inspector v0.12.8
Visit http://127.0.0.1:8080/?port=5858 to start debugging.
Error: listen EADDRINUSE
    at exports._errnoException (util.js:746:11)
    at Agent.Server._listen2 (net.js:1158:14)
    at listen (net.js:1184:10)
    at Agent.Server.listen (net.js:1269:5)
    at Object.start (_debugger_agent.js:20:9)
    at startup (node.js:86:9)
    at node.js:814:3
Cannot send response - there is no front-end connection.
```

Everything seems to work despite the error.
Perhaps both node processes trying to open port 5858?

**Comment by TheGoldenEye** [comment]
The issue is, that the dapp processes try to use the same debugging port as the main process.
The PR #3 allows an new unique debugging port for each blockchain app.
